### ISSUE TITLE
no fold

### ISSUE THREAD

**Issue by step-** [ZSaberLv0/ZFVimFoldBlock#1]
Hi, thank you for this plugin.

```
#DELETE:MNTDIR=$(echo $APPDIR | sed 's,/*[^/]\+/*$,,')
MNTDIR="${APPDIR%/*}"
```
Does not fold the top line for `:ZFFoldBlock /#DELETE://`. Other lines with that prefix fold correctly. Can you reproduce?

Your searchfold.vim plugin has trouble with those lines, too. It folds both instead of just the top line.

**Comment by ZSaberLv0** [comment]
@step- sorry for my late, this issue should have been fixed (forgot when, though), won't happen for my case, please try the latest version?

**Comment by step-** [comment]
> please try the latest version?
Do you have a version more recent than Nov 20, 2017 when I opened this issue?

**Comment by ZSaberLv0** [comment]
have you try `set foldminlines=0` ?

i have tested at vim/gvim, version 7.3/8.0

if still occurred, could you please supply your full example text, vim version and OS?

**Comment by step-** [comment]
OK, it works with `set foldminlines=0`. Thank you.
